import { chromium } from 'playwright'
import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const output = join(dirname(fileURLToPath(import.meta.url)), '..', 'test-results')
const baseUrl = process.env.BASE_URL || 'http://localhost:5173'
await mkdir(output, { recursive: true })

const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
const errors = []
page.on('console', (message) => message.type() === 'error' && errors.push(message.text()))
page.on('pageerror', (error) => errors.push(error.message))

await page.goto(baseUrl, { waitUntil: 'networkidle' })
await page.getByRole('heading', { name: 'Acesse seu portal' }).waitFor()
await page.screenshot({ path: join(output, 'login-desktop.png'), fullPage: true })

await page.getByRole('button', { name: 'Entrar', exact: true }).click()
await page.waitForURL('**/dashboard')
await page.getByRole('heading', { name: /Olá, Marina/ }).waitFor()
await page.screenshot({ path: join(output, 'dashboard-desktop.png'), fullPage: true })

await page.goto(`${baseUrl}/contents/festival-de-massas`, { waitUntil: 'networkidle' })
await page.getByRole('heading', { name: 'Festival de Massas', exact: true, level: 1 }).waitFor()
await page.screenshot({ path: join(output, 'review-desktop.png'), fullPage: true })
await page.getByRole('button', { name: 'Aprovar conteúdo' }).click()
await page.getByRole('heading', { name: 'Aprovar este conteúdo?' }).waitFor()
await page.waitForTimeout(300)
await page.screenshot({ path: join(output, 'approval-modal.png'), fullPage: true })
await page.getByRole('button', { name: 'Fechar' }).click()
await page.getByRole('button', { name: 'Solicitar alteração' }).click()
await page.getByRole('heading', { name: 'O que precisa mudar?' }).waitFor()
await page.waitForTimeout(300)
await page.screenshot({ path: join(output, 'changes-modal.png'), fullPage: true })
await page.getByRole('button', { name: 'Fechar' }).click()
await page.getByRole('button', { name: 'Prévia no canal' }).click()
await page.getByRole('heading', { name: 'Prévia no canal' }).waitFor()
await page.screenshot({ path: join(output, 'social-preview-instagram.png'), fullPage: true })
await page.getByRole('button', { name: 'Próxima imagem' }).click()
await page.getByText('2/3', { exact: true }).waitFor()
const carousel = page.locator('.social-media-carousel')
const carouselBox = await carousel.boundingBox()
if (!carouselBox) throw new Error('Carrossel da prévia não encontrado.')
await page.mouse.move(carouselBox.x + carouselBox.width * .7, carouselBox.y + carouselBox.height / 2)
await page.mouse.down()
await page.mouse.move(carouselBox.x + carouselBox.width * .3, carouselBox.y + carouselBox.height / 2)
await page.mouse.up()
await page.getByText('3/3', { exact: true }).waitFor()
await page.getByRole('button', { name: 'Ver imagem 1' }).click()
await page.getByText('1/3', { exact: true }).waitFor()
await page.screenshot({ path: join(output, 'social-preview-carousel.png'), fullPage: true })
await page.getByRole('button', { name: /TikTok/ }).click()
await page.getByText('@sabor.davila').waitFor()
await page.screenshot({ path: join(output, 'social-preview-tiktok.png'), fullPage: true })
await page.getByRole('button', { name: 'Fechar prévia' }).click()
await page.getByRole('button', { name: 'Briefing' }).click()
await page.getByRole('heading', { name: 'O que você precisa saber' }).waitFor()
await page.screenshot({ path: join(output, 'review-briefing-desktop.png'), fullPage: true })
await page.getByRole('button', { name: 'Versões' }).click()
await page.getByRole('heading', { name: '3 versões desta peça' }).waitFor()
await page.getByRole('button', { name: /Comentários/ }).click()

await page.setViewportSize({ width: 390, height: 844 })
await page.reload({ waitUntil: 'networkidle' })
await page.getByRole('heading', { name: 'Festival de Massas', exact: true, level: 1 }).waitFor()
await page.screenshot({ path: join(output, 'review-mobile.png'), fullPage: true })
await page.getByRole('button', { name: 'Prévia no canal' }).click()
await page.getByRole('heading', { name: 'Prévia no canal' }).waitFor()
await page.getByRole('button', { name: 'Próxima imagem' }).click()
await page.getByText('2/3', { exact: true }).waitFor()
await page.screenshot({ path: join(output, 'social-preview-mobile.png'), fullPage: true })
await page.getByRole('button', { name: 'Fechar prévia' }).click()
await page.getByRole('button', { name: /Revisão/ }).click()
await page.getByRole('heading', { name: 'Revise em conjunto' }).waitFor()
await page.screenshot({ path: join(output, 'review-panel-mobile.png'), fullPage: true })

await browser.close()
if (errors.length) throw new Error(`Erros no navegador:\n${errors.join('\n')}`)
console.log('QA visual concluído: login, dashboard e revisão em desktop/mobile.')
